### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Exited with code 3

### ISSUE THREAD

**Issue by haohonglong** [fecshop/vue_fecshop_appserver#7]
node 版本:v12.14.1
npm 版本: 6.13.4

请问下面的问题怎么解决呢？
(node:370) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.<anonymous> (/www/fecshop/vue_fecshop_appserver/node_modules/opn/index.js:83:13)
    at Object.onceWrapper (events.js:313:26)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:223:5)
    at Pipe.<anonymous> (net.js:664:12)
(node:370) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:370) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
webpack built 092b1b44814c1cf80b75 in 15349ms
Hash: 092b1b44814c1cf80b75
Version: webpack 1.15.0
Time: 15349ms

**Comment by fancyecommerce** [comment]
有问题，直接官网论坛发帖子：http://www.fecmall.com/topic
